import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <>
      <h1>About page</h1>
      <p>
        Go to <Link href="/">Home page</Link>
      </p>
    </>
  );
};

export default AboutPage;
