import type { Metadata } from 'next'

const websiteUrl = process.env.NODE_ENV === 'production' ? 'https://acme.com' : 'http://localhost:3000'

export const globalMetadataConfig = {
  title: 'Next.js & Chakra UI Starter',
  description: 'Generated by create next app',
}

export const globalMetadata: Metadata = {
  metadataBase: new URL(websiteUrl),
  title: {
    template: `%s | ${globalMetadataConfig.title}`,
    default: globalMetadataConfig.title,
  },
  description: globalMetadataConfig.description,
  openGraph: {
    title: globalMetadataConfig.title,
    description: globalMetadataConfig.description,
    url: websiteUrl,
    siteName: globalMetadataConfig.title,
    images: [
      {
        url: `${websiteUrl}/og-image.png`, // Must be an absolute URL
        width: 800,
        height: 600,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
}
