import type { Metadata } from 'next'

import HomeHero from '@/components/organisms/HomeHero'

export const metadata: Metadata = {
  title: 'Welcome',
  description: 'Generated by create next app',
}

/**
 * If you need to use hooks on this page, extract the logic to a custom component instead.
 * This is because hooks can only be used inside *client* components marked as `use client`.
 */
const HomePage = () => {
  return (
    <>
      <HomeHero />
    </>
  )
}

export default HomePage
