import type { Metadata } from "next";
import Link from "next/link";

import { Heading, Text } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <>
      <Heading as="h1">
        Hey there! Glebovsky still rocks, but the site will be available
        later...
      </Heading>
      <Text>
        Go to <Link href="/about">About page</Link>
      </Text>
    </>
  );
};

export default HomePage;
