import type { Metadata } from 'next'
import Link from 'next/link'

import { Heading, Text } from '@chakra-ui/react'
import Section from '@/components/Section'

export const metadata: Metadata = {
  title: 'Welcome',
  description: 'Generated by create next app',
}

const HomePage = () => {
  return (
    <Section>
      <Heading as="h1">Hey there! Glebovsky still rocks, but the site will be available later...</Heading>
      <Text>
        Go to <Link href="/about">About page</Link>
      </Text>
    </Section>
  )
}

export default HomePage
